app/base/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_login import UserMixin
from sqlalchemy import Binary, Column, Integer, String
from sqlalchemy.sql.sqltypes import Date, PickleType
import time
from app import db, login_manager
import datetime
from app.base.util import hash_pass

class User(db.Model, UserMixin):

    __tablename__ = 'User'

    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True)
    email = Column(String, unique=True)
    password = Column(Binary)

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass( value ) # we need bytes here (not plain str)
                
            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return User.query.filter_by(id=id).first()

@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = User.query.filter_by(username=username).first()
    return user if user else None

class Picks(db.Model):

    __tablename__ = 'Picks'

    id = Column(Integer, primary_key=True)
    pick = Column(PickleType)
    direction = Column(String, unique=True)
    bearish = Column(Integer)
    neutral = Column(Integer)
    bullish = Column(Integer)
    total = Column(Integer)
    time= Column(Date, default=datetime.datetime.utcnow())

    #def __init__(self, **kwargs):
        # for property, value in kwargs.items():
        #     if hasattr(value, '__iter__') and not isinstance(value, str):
        #         value = value[0]
        #     if property == 'time':
        #         value = time.ctime() # we need bytes here (not plain str)
        # setattr(self, property, value)
    def __repr__(self):
        return "class picks id is " + str(self.id)

app/base/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField
from wtforms.validators import InputRequired, Email, DataRequired

## login and registration

class LoginForm(FlaskForm):
    username = TextField    ('Username', id='username_login'   , validators=[DataRequired()])
    password = PasswordField('Password', id='pwd_login'        , validators=[DataRequired()])

class CreateAccountForm(FlaskForm):
    username = TextField('Username'     , id='username_create' , validators=[DataRequired()])
    email    = TextField('Email'        , id='email_create'    , validators=[DataRequired(), Email()])
    password = PasswordField('Password' , id='pwd_create'      , validators=[DataRequired()])

app/base/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'base_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

app/base/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import jsonify, render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user
)

from app import db, login_manager
from app.base import blueprint
from app.base.forms import LoginForm, CreateAccountForm
from app.base.models import User
import config
from app.base.util import verify_pass

@blueprint.route('/')
def route_default():
    if config.Config.allowLogin:
        return redirect(url_for('base_blueprint.login'))
    else:
        return redirect(url_for('home_blueprint.index'))

## Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:
        
        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = User.query.filter_by(username=username).first()
        
        # Check the password
        if user and verify_pass( password, user.password):

            login_user(user)
            return redirect(url_for('base_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template( 'accounts/login.html', msg='Wrong user or password', form=login_form)

    if not current_user.is_authenticated:
        return render_template( 'accounts/login.html',
                                form=login_form)
    return redirect(url_for('home_blueprint.index'))

@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    login_form = LoginForm(request.form)
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username  = request.form['username']
        email     = request.form['email'   ]

        # Check usename exists
        user = User.query.filter_by(username=username).first()
        if user:
            return render_template( 'accounts/register.html', 
                                    msg='Username already registered',
                                    success=False,
                                    form=create_account_form)

        # Check email exists
        user = User.query.filter_by(email=email).first()
        if user:
            return render_template( 'accounts/register.html', 
                                    msg='Email already registered', 
                                    success=False,
                                    form=create_account_form)

        # else we can create the user
        user = User(**request.form)
        db.session.add(user)
        db.session.commit()

        return render_template( 'accounts/register.html', 
                                msg='User created please <a href="/login">login</a>', 
                                success=True,
                                form=create_account_form)

    else:
        return render_template( 'accounts/register.html', form=create_account_form)

@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/shutdown')
def shutdown():
    func = request.environ.get('werkzeug.server.shutdown')
    if func is None:
        raise RuntimeError('Not running with the Werkzeug Server')
    func()
    return 'Server shutting down...'

## Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('errors/403.html'), 403

@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('errors/403.html'), 403

@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('page-404.html'), 404

@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('errors/500.html'), 500

app/base/templates/accounts/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card-group">
        <div class="card p-4">
          <div class="card-body">
            <h1>Login</h1>
            <p class="text-muted">

              {% if msg %}
                {{ msg | safe }}
              {% else %}              
                Use default credentials: test / pass
              {% endif %}  
            </p>

            <form role="form" method="post" action="">

              {{ form.hidden_tag() }} 

              <div class="input-group mb-3">
                <div class="input-group-prepend"><span class="input-group-text">
                    <svg class="c-icon">
                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-user"></use>
                    </svg></span></div>
                    {{ form.username(placeholder="Username", class="form-control") }}
              </div>

              <div class="input-group mb-4">
                <div class="input-group-prepend"><span class="input-group-text">
                    <svg class="c-icon">
                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-lock-locked"></use>
                    </svg></span></div>
                    {{ form.password(placeholder="Password", class="form-control", type="password") }}
              </div>

              <div class="row">
                <div class="col-6">
                  <button type="submit" name="login" class="btn btn-primary px-4">Login</button>
                </div>
                <div class="col-6 text-right">
                  <a href={{ url_for('base_blueprint.register') }} class="btn btn-link px-0">Register</a>
                </div>
              </div>
            
            </form> 

          </div>
        </div>
        <div class="card text-white bg-primary py-5 d-md-down-none" style="width:44%">
          <div class="card-body text-center">
            
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

app/base/templates/includes/footer.html
    <footer class="c-footer">
        <div>
            &copy; <a target="_blank" href="http://wsb-reddit.herokuapp.com/">Reddit Analyzer</a> - Coded by <a target="_blank" href=#>Danksta</a> and <a target="_blank" href='https://github.com/asad70'>asad70</a>.
        </div>
        <div class="ml-auto">
            <a target="_blank" href="http://wsb-reddit.herokuapp.com/">Reddit-analyzer</a>
        </div>
    </footer>

app/base/templates/includes/navigation.html
      <header class="c-header c-header-light c-header-fixed c-header-with-subheader">
        <button class="c-header-toggler c-class-toggler d-lg-none mfe-auto" type="button" data-target="#sidebar" data-class="c-sidebar-show">
          <svg class="c-icon c-icon-lg">
            <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-menu"></use>
          </svg>
        </button><a class="c-header-brand d-lg-none" href="#">
          <svg width="118" height="46" alt="CoreUI Logo">
            <use xlink:href="/static/assets/brand/coreui.svg#full"></use>
          </svg></a>
        <button class="c-header-toggler c-class-toggler mfs-3 d-md-down-none" type="button" data-target="#sidebar" data-class="c-sidebar-lg-show" responsive="true">
          <svg class="c-icon c-icon-lg">
            <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-menu"></use>
          </svg>
        </button>
        <ul class="c-header-nav d-md-down-none">
          <li class="c-header-nav-item px-3"><a class="c-header-nav-link" href="#">Dashboard</a></li>
          <li class="c-header-nav-item px-3"><a class="c-header-nav-link" href="#">Users</a></li>
          <li class="c-header-nav-item px-3"><a class="c-header-nav-link" href="#">Settings</a></li>
        </ul>
        <ul class="c-header-nav ml-auto mr-4">
          <li class="c-header-nav-item d-md-down-none mx-2"><a class="c-header-nav-link" href="#">
              <svg class="c-icon">
                <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-bell"></use>
              </svg></a></li>
          <li class="c-header-nav-item d-md-down-none mx-2"><a class="c-header-nav-link" href="#">
              <svg class="c-icon">
                <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-list-rich"></use>
              </svg></a></li>
          <li class="c-header-nav-item d-md-down-none mx-2"><a class="c-header-nav-link" href="#">
              <svg class="c-icon">
                <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-envelope-open"></use>
              </svg></a></li>
          <li class="c-header-nav-item dropdown"><a class="c-header-nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              <div class="c-avatar"><img class="c-avatar-img" src="/static/assets/img/avatars/6.jpg" alt="user@email.com"></div>
            </a>
            <div class="dropdown-menu dropdown-menu-right pt-0">
              <div class="dropdown-header bg-light py-2"><strong>Account</strong></div><a class="dropdown-item" href="#">
                <svg class="c-icon mr-2">
                  <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-bell"></use>
                </svg> Updates<span class="badge badge-info ml-auto">42</span></a><a class="dropdown-item" href="#">
                <svg class="c-icon mr-2">
                  <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-envelope-open"></use>
                </svg> Messages<span class="badge badge-success ml-auto">42</span></a><a class="dropdown-item" href="#">
                <svg class="c-icon mr-2">
                  <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-task"></use>
                </svg> Tasks<span class="badge badge-danger ml-auto">42</span></a><a class="dropdown-item" href="#">
                <svg class="c-icon mr-2">
                  <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-comment-square"></use>
                </svg> Comments<span class="badge badge-warning ml-auto">42</span></a>
              <div class="dropdown-header bg-light py-2"><strong>Settings</strong></div><a class="dropdown-item" href="#">
                <svg class="c-icon mr-2">
                  <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-user"></use>
                </svg> Profile</a><a class="dropdown-item" href="#">
                <svg class="c-icon mr-2">
                  <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-settings"></use>
                </svg> Settings</a><a class="dropdown-item" href="#">
                <svg class="c-icon mr-2">
                  <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-credit-card"></use>
                </svg> Payments<span class="badge badge-secondary ml-auto">42</span></a><a class="dropdown-item" href="#">
                <svg class="c-icon mr-2">
                  <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-file"></use>
                </svg> Projects<span class="badge badge-primary ml-auto">42</span></a>
              <div class="dropdown-divider"></div><a class="dropdown-item" href="#">
                <svg class="c-icon mr-2">
                  <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-lock-locked"></use>
                </svg> Lock Account</a>
                <a class="dropdown-item" href={{ url_for('base_blueprint.logout') }} >
                <svg class="c-icon mr-2">
                  <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-account-logout"></use>
                </svg> Logout</a>
            </div>
          </li>
        </ul>
        <div class="c-subheader px-3">
          <!-- Breadcrumb-->
          <ol class="breadcrumb border-0 m-0">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item"><a href="#">Admin</a></li>
            <li class="breadcrumb-item active">Dashboard</li>
            <!-- Breadcrumb Menu-->
          </ol>
        </div>
      </header>

app/base/templates/includes/scripts.html
    <!-- CoreUI and necessary plugins-->
    <script src="/static/assets/vendors/@coreui/coreui/js/coreui.bundle.min.js"></script>
    <!--[if IE]><!-->
    <script src="/static/assets/vendors/@coreui/icons/js/svgxuse.min.js"></script>

      

app/base/templates/includes/sidebar.html
    <div class="c-sidebar c-sidebar-dark c-sidebar-fixed c-sidebar-lg-show" id="sidebar">
        <div class="c-sidebar-brand d-lg-down-none">
          <svg class="c-sidebar-brand-full" width="118" height="46" alt="CoreUI Logo">
            <use xlink:href="/static/assets/brand/coreui.svg#full"></use>
          </svg>
          <svg class="c-sidebar-brand-minimized" width="46" height="46" alt="CoreUI Logo">
            <use xlink:href="/static/assets/brand/coreui.svg#signet"></use>
          </svg>
        </div>
        <ul class="c-sidebar-nav">
          <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/reddit-index">
            <svg class="c-sidebar-nav-icon">
              <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-chart-pie"></use>
            </svg> Reddit results</a></li>
          <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/index1">
              <svg class="c-sidebar-nav-icon">
                <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-speedometer"></use>
              </svg> Dashboard<span class="badge badge-info">NEW</span></a></li>
          <li class="c-sidebar-nav-title">Theme</li>
          <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/ui-colors.html">
              <svg class="c-sidebar-nav-icon">
                <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-drop1"></use>
              </svg> Colors</a></li>
          <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/ui-typography.html">
              <svg class="c-sidebar-nav-icon">
                <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-pencil"></use>
              </svg> Typography</a></li>
          <li class="c-sidebar-nav-title">Components</li>
          <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/reddit-index.html">
              <svg class="c-sidebar-nav-icon">
                <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-chart-pie"></use>
              </svg> Reddit results</a></li>
          <li class="c-sidebar-nav-item c-sidebar-nav-dropdown"><a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="#">
              <svg class="c-sidebar-nav-icon">
                <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-puzzle"></use>
              </svg> Baseee</a>
            <ul class="c-sidebar-nav-dropdown-items">
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/ui-breadcrumb.html"><span class="c-sidebar-nav-icon"></span> Breadcrumb</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/ui-cards.html"><span class="c-sidebar-nav-icon"></span> Cards</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/ui-carousel.html"><span class="c-sidebar-nav-icon"></span> Carousel</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/ui-collapse.html"><span class="c-sidebar-nav-icon"></span> Collapse</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/ui-forms.html"><span class="c-sidebar-nav-icon"></span> Forms</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/ui-jumbotron.html"><span class="c-sidebar-nav-icon"></span> Jumbotron</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/ui-list-group.html"><span class="c-sidebar-nav-icon"></span> List group</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/ui-navs.html"><span class="c-sidebar-nav-icon"></span> Navs</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/ui-pagination.html"><span class="c-sidebar-nav-icon"></span> Pagination</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/ui-popovers.html"><span class="c-sidebar-nav-icon"></span> Popovers</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/ui-progress.html"><span class="c-sidebar-nav-icon"></span> Progress</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/ui-scrollspy.html"><span class="c-sidebar-nav-icon"></span> Scrollspy</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/ui-switches.html"><span class="c-sidebar-nav-icon"></span> Switches</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/ui-tables.html"><span class="c-sidebar-nav-icon"></span> Tables</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/ui-tabs.html"><span class="c-sidebar-nav-icon"></span> Tabs</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/ui-tooltips.html"><span class="c-sidebar-nav-icon"></span> Tooltips</a></li>
            </ul>
          </li>
          <li class="c-sidebar-nav-item c-sidebar-nav-dropdown"><a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="#">
              <svg class="c-sidebar-nav-icon">
                <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-cursor"></use>
              </svg> Buttons</a>
            <ul class="c-sidebar-nav-dropdown-items">
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/buttons.html"><span class="c-sidebar-nav-icon"></span> Buttons</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/buttons-group.html"><span class="c-sidebar-nav-icon"></span> Buttons Group</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/buttons-dropdowns.html"><span class="c-sidebar-nav-icon"></span> Dropdowns</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/buttons-brand.html"><span class="c-sidebar-nav-icon"></span> Brand Buttons</a></li>
            </ul>
          </li>
          <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/page-charts.html">
              <svg class="c-sidebar-nav-icon">
                <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-chart-pie"></use>
              </svg> Charts</a></li>
          <li class="c-sidebar-nav-dropdown"><a class="c-sidebar-nav-dropdown-toggle" href="#">
              <svg class="c-sidebar-nav-icon">
                <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-star"></use>
              </svg> Icons</a>
            <ul class="c-sidebar-nav-dropdown-items">
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/icons-free.html"> CoreUI Icons<span class="badge badge-success">Free</span></a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/icons-brand.html"> CoreUI Icons - Brand</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/icons-flag.html"> CoreUI Icons - Flag</a></li>
            </ul>
          </li>
          <li class="c-sidebar-nav-item c-sidebar-nav-dropdown"><a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="#">
              <svg class="c-sidebar-nav-icon">
                <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-bell"></use>
              </svg> Notifications</a>
            <ul class="c-sidebar-nav-dropdown-items">
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/notifications-alerts.html"><span class="c-sidebar-nav-icon"></span> Alerts</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/notifications-badge.html"><span class="c-sidebar-nav-icon"></span> Badge</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/notifications-modals.html"><span class="c-sidebar-nav-icon"></span> Modals</a></li>
            </ul>
          </li>
          <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/page-widgets.html">
              <svg class="c-sidebar-nav-icon">
                <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-calculator"></use>
              </svg> Widgets<span class="badge badge-info">NEW</span></a></li>
          <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href={{ url_for('base_blueprint.logout') }} >
            <svg class="c-sidebar-nav-icon">
              <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-account-logout"></use>
            </svg> Logout</a></li>

          <li class="c-sidebar-nav-divider"></li>
          <li class="c-sidebar-nav-title">Extras</li>
          <li class="c-sidebar-nav-item c-sidebar-nav-dropdown"><a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="#">
              <svg class="c-sidebar-nav-icon">
                <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-star"></use>
              </svg> Pages</a>
            <ul class="c-sidebar-nav-dropdown-items">
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/sign-in.html" target="_top">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-account-logout"></use>
                  </svg> Login</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/sign-up.html" target="_top">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-account-logout"></use>
                  </svg> Register</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/page-404.html" target="_top">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-bug"></use>
                  </svg> Error 404</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/page-500.html" target="_top">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-bug"></use>
                  </svg> Error 500</a></li>
            </ul>
          </li>
          <li class="c-sidebar-nav-item mt-auto">
              <a class="c-sidebar-nav-link c-sidebar-nav-link-success" href="https://appseed.us/admin-dashboards/flask-dashboard-coreui" target="_blank">
              <svg class="c-sidebar-nav-icon">
                <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-cloud-download"></use>
              </svg> See Product</a></li>
          <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link c-sidebar-nav-link-danger" href="https://appseed.us/admin-dashboards/flask" target="_blank">
              <svg class="c-sidebar-nav-icon">
                <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-layers"></use>
              </svg> More Starters</a></li>
        </ul>
        <button class="c-sidebar-minimizer c-class-toggler" type="button" data-target="_parent" data-class="c-sidebar-minimized"></button>
      </div>